### Scalar

In [1]:
import numpy as np

In [45]:
l = []

l.append(np.random.rand(1,3))
l.append(np.random.rand(1,3))
l.append(np.random.rand(1,3))

print('l:')
print(l)

n = np.stack(l)
print('n:')
print(n)

n = n.reshape(-1, 3)
print('n')
print(n)

l:
[array([[0.1030349 , 0.85842076, 0.11692744]]), array([[0.75736717, 0.42468888, 0.64777084]]), array([[0.11558322, 0.83661577, 0.69405407]])]
n:
[[[0.1030349  0.85842076 0.11692744]]

 [[0.75736717 0.42468888 0.64777084]]

 [[0.11558322 0.83661577 0.69405407]]]
n
[[0.1030349  0.85842076 0.11692744]
 [0.75736717 0.42468888 0.64777084]
 [0.11558322 0.83661577 0.69405407]]


array([[[0.54817451, 0.14644175, 0.34113273]],

       [[0.98749246, 0.27940294, 0.63666397]],

       [[0.67115177, 0.87490979, 0.6052869 ]]])

In [41]:
n = n.reshape(-1, 3)

In [42]:
n.shape

(3, 3)

In [ ]:
np.stack(l).

In [3]:
s = np.array(5)
print(s.shape)
x = s + 3
print(x)

()
8


In [5]:
c = np.array(10)
c.shape

()

### Vector

In [8]:
v = np.array([1,2,3,4])
v.shape

(4,)

In [11]:

k = v[2:]

In [12]:
k

array([3, 4])

### Matrix

In [25]:
m = np.array([[1,2,3,4], [4,5,6,7], [7,8,9,10], [7,8,9,10]])
m.shape

(4, 4)

In [26]:
m

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [ 7,  8,  9, 10]])

In [27]:
m[:, 1:]

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [ 8,  9, 10]])

In [43]:
n = m[:-1,:][:, 1:3]
print(n)

[[2 3]
 [5 6]
 [8 9]]


In [ ]:
n[1:3]

### Tensor

In [10]:
t = np.array([\
[[[1],[2]], [[3], [4]], [[5], [6]]],\
[[[7],[8]], [[9], [10]], [[11], [12]]],\
[[[13],[14]], [[15], [16]], [[17], [18]]]\
])
t.shape

(3, 3, 2, 1)

### Change Shape

In [11]:
v = np.array([1,2,3,4])
#v.reshape(1,4).shape
v[None,:]
v[:, None]
v.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [47]:
v = np.array([1,2,3,4,5,6,7,8])
print(v)

[1 2 3 4 5 6 7 8]


In [60]:
k = v.reshape((4,2))
print(k)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [61]:
k.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [58]:
np.random.rand(5,6).T

array([[0.57953691, 0.8957018 , 0.46912373, 0.65467364, 0.55693794],
       [0.36123147, 0.43754191, 0.92198625, 0.23099448, 0.98303344],
       [0.24122835, 0.04515992, 0.30023606, 0.27398201, 0.0057437 ],
       [0.79321305, 0.358936  , 0.87919962, 0.61510849, 0.25468298],
       [0.74169926, 0.08999628, 0.22294322, 0.75265429, 0.63250659],
       [0.02639395, 0.59737409, 0.48730411, 0.49474215, 0.61551166]])

In [13]:
W = np.random.rand(2,1)
X = np.array([[ 0.78051,   -0.063669 ],
 [ 0.28774,    0.29139  ],
 [ 0.40714,    0.17878  ],
 [ 0.2923 ,    0.4217   ]])

W.shape
X.shape
np.matmul(X, W)

array([[0.6278701 ],
       [0.51231912],
       [0.51661059],
       [0.63255313]])

In [14]:
np.exp([1,2,3,5])

array([  2.71828183,   7.3890561 ,  20.08553692, 148.4131591 ])

In [15]:
def cross_entropy(Y, P):
    Y = np.float_(Y)
    print(Y)
    P = np.float_(P)
    print(P)
    print(np.log(P))
    print(Y*np.log(P))
    print((1 - Y) * np.log(1 - P))
    return -np.sum(Y * np.log(P) + (1 - Y) * np.log(1 - P))

Y = np.array([1,1,0])
P = np.array([0.8, 0.7, 0.1])
cross_entropy(Y, P)

[1. 1. 0.]
[0.8 0.7 0.1]
[-0.22314355 -0.35667494 -2.30258509]
[-0.22314355 -0.35667494 -0.        ]
[-0.         -0.         -0.10536052]


0.6851790109107685

In [16]:
x = np.array([1, 2, 3, 4])
y = np.array(0.5)

# Initial weights
w = np.array([0.5, -0.5, 0.3, 0.1])

### Calculate one gradient descent step for each weight
### Note: Some steps have been consilated, so there are
###       fewer variable names than in the above sample code

# TODO: Calculate the node's linear combination of inputs and weights
h = np.matmul(x, w.T)
print(h)


0.7999999999999998


In [17]:
weights = np.random.normal(scale=1 / 6**.5, size=6)
np.random.normal(0, 6**-0.5, size=(6, 2))

np.random.seed(42)
# Make some fake data
np.random.randn(4)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986])

In [18]:
np.array([2,2]) * np.array([1,3])

array([2, 6])

In [25]:
a = np.array([1,2,3,4,5]).reshape(1,5)
a[0][1] = 10
print(a)

[[ 1 10  3  4  5]]


In [62]:
a = np.array([[1,2,3,4], [4,5,6,7], [7,8,9,10]])
b = np.array([[11], [12], [13]])
print(a)
print(b)
c = np.concatenate((a,b), axis=1)
print(c)
print(c.shape)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
[[11]
 [12]
 [13]]
[[ 1  2  3  4 11]
 [ 4  5  6  7 12]
 [ 7  8  9 10 13]]
(3, 5)


In [1]:
[1,2,3]*3


[1, 2, 3, 1, 2, 3, 1, 2, 3]