In [1]:
import torch

In [2]:
def activate(x):
    return 1/(1+torch.exp(-x))

In [3]:
torch.manual_seed(7)

In [4]:
features = torch.randn((1,5))

In [5]:
features

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])

In [7]:
weights = torch.randn_like(features)

In [8]:
bias = torch.randn((1,1))

In [9]:
bias

tensor([[1.3470]])

In [10]:
features.matmul(weights)

RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at /Users/administrator/nightlies/pytorch-1.0.0/wheel_build_dirs/conda_3.6/conda/conda-bld/pytorch_1544137972173/work/aten/src/TH/generic/THTensorMath.cpp:940

In [13]:
features = features.view(5,1)

In [20]:
features = torch.randn((1,5))
weights = torch.randn_like(features)
weights = weights.view(5,1)
bias = torch.randn((1,1))
features.matmul(weights) + bias


tensor([[-1.6951]])

In [25]:
torch.manual_seed(7)

features = torch.randn((1,4))

n_input = features.shape[1]
n_hidden = 20
n_output = 3

W1 = torch.randn((n_input, n_hidden))
W2 = torch.randn((n_hidden, n_output))

B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))


hidden_out = activate(features.mm(W1) + B1)

out = activate(hidden_out.mm(W2) + B2)

print('hidden out %s, out %s' % (
    hidden_out.shape, 
    out.shape
))



hidden out torch.Size([1, 20]), out torch.Size([1, 3])


In [26]:
import numpy as np

In [27]:
a = np.random.rand(4,3)

In [28]:
b = torch.from_numpy(a)
b

tensor([[0.4015, 0.7468, 0.2226],
        [0.7833, 0.5142, 0.1411],
        [0.9769, 0.6361, 0.4606],
        [0.4149, 0.0798, 0.4038]], dtype=torch.float64)

In [29]:
b.numpy()

array([[0.40151897, 0.74675015, 0.22259794],
       [0.78325013, 0.51417027, 0.14109984],
       [0.97688448, 0.63610323, 0.4606475 ],
       [0.41488495, 0.07976179, 0.4038156 ]])

In [30]:
b.mul_(2)

tensor([[0.8030, 1.4935, 0.4452],
        [1.5665, 1.0283, 0.2822],
        [1.9538, 1.2722, 0.9213],
        [0.8298, 0.1595, 0.8076]], dtype=torch.float64)